# Generated by Django 4.2.4 on 2023-08-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_restclothes_shoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=2)),
                ('opinion', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Restclothes',
        ),
        migrations.DeleteModel(
            name='Shoes',
        ),
        migrations.RemoveField(
            model_name='clothing',
            name='rating',
        ),
        migrations.AddField(
            model_name='clothing',
            name='type',
            field=models.CharField(default='Brak informacji', max_length=100),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='description',
            field=models.TextField(max_length=300),
        ),
    ]
