# Generated by Django 4.2.4 on 2023-08-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rates_delete_restclothes_delete_shoes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothing',
            name='size',
            field=models.FloatField(default=0),
        ),
    ]
