# Generated by Django 4.2.4 on 2023-08-25 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_clothing_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='rates',
            name='clothing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.clothing'),
        ),
    ]
