# Generated by Django 4.2.4 on 2023-08-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rates_clothing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rates',
            name='rate',
            field=models.IntegerField(),
        ),
    ]
