# Generated by Django 4.2.4 on 2023-09-01 20:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_rates_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='rates',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
